# Generated by Django 5.1 on 2025-10-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_info',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedrift_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bedrift_info',
            name='tiltaleform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
