# Generated by Django 5.1 on 2025-10-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('store', '0002_bedrift_info_user_alter_bedrift_info_tiltaleform'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_jobs', to='store.bedrift_info')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributed_to', to='core.flytteforesporsel')),
            ],
        ),
    ]
