# Generated by Django 5.1 on 2024-10-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_membership_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
