# Generated by Django 4.2.4 on 2023-08-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='bid_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
