# Generated by Django 5.1 on 2025-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_jobdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_info',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bedrift_info',
            name='leads_per_day',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='bedrift_info',
            name='leads_per_month',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='bedrift_info',
            name='leads_per_week',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
