# Generated by Django 4.2.4 on 2023-08-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_bud_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bud',
            name='bidder_name',
        ),
        migrations.AddField(
            model_name='bud',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bud', to=settings.AUTH_USER_MODEL),
        ),
    ]
