# Generated by Django 5.1 on 2025-10-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('store', '0004_bedrift_info_active_bedrift_info_leads_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdistribution',
            name='slot_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business 1'), (2, 'Business 2'), (3, 'Business 3')], help_text='Which slot this business occupies for this inquiry.', null=True),
        ),
        migrations.AlterField(
            model_name='jobdistribution',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.flytteforesporsel'),
        ),
    ]
