# Generated by Django 5.1 on 2025-10-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_jobdistribution_slot_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdistribution',
            name='business',
        ),
        migrations.RemoveField(
            model_name='jobdistribution',
            name='slot_number',
        ),
        migrations.AddField(
            model_name='jobdistribution',
            name='business_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_primary', to='store.bedrift_info', verbose_name='Business 1'),
        ),
        migrations.AddField(
            model_name='jobdistribution',
            name='business_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_secondary', to='store.bedrift_info', verbose_name='Business 2'),
        ),
        migrations.AddField(
            model_name='jobdistribution',
            name='business_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_tertiary', to='store.bedrift_info', verbose_name='Business 3'),
        ),
    ]
