# Generated by Django 4.2.4 on 2023-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_bud_bidder_name_bud_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bud',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='bud',
            name='declined',
        ),
        migrations.AddField(
            model_name='bud',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
