# Generated by Django 4.2.4 on 2023-08-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_bud_accepted_remove_bud_declined_bud_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='car',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='store.car'),
        ),
    ]
