# Generated by Django 5.1 on 2025-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_jobdistribution_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_info',
            name='total_leads_received',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
