# Generated by Django 4.2.4 on 2023-08-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_bud_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='car',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='store.car'),
        ),
    ]
