# Generated by Django 5.1 on 2025-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_bedrift_info_total_leads_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrift_info',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
