# Generated by Django 5.1 on 2025-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_publicbusinessinformation_businessimage_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_info',
            name='priority_score',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
