# Generated by Django 4.2.4 on 2023-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_car_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='sold',
        ),
    ]
