# Generated by Django 4.2.4 on 2023-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_car_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
    ]
