# Generated by hand, following the shape `makemigrations` would produce for
# this exact model diff (the project's local venv is broken on this machine —
# see apps/store/migrations/0011_normalize_leads_priority_data.py for why the
# preceding data migration exists).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_normalize_leads_priority_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrift_info',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bedrift_info',
            name='total_leads_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bedrift_info',
            name='priority_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
