# Generated by Django 4.2.4 on 2023-08-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image1',
            field=models.ImageField(default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image10',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image4',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image5',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image6',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image7',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image8',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image9',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
    ]
