# Generated by Django 4.1.5 on 2026-08-26 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_bedrift_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_info',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bedrift_info',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bedrift_info',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Skriv inn et gyldig telefonnummer (tall, mellomrom og +/-/() tillatt).', regex='^[0-9+\\-\\s()]{6,20}$')]),
        ),
    ]
