# Generated by Django 4.2.4 on 2023-08-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_car_image1_alter_car_image10_alter_car_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('date1', models.CharField(blank=True, max_length=100, null=True)),
                ('time1_1', models.CharField(blank=True, max_length=100, null=True)),
                ('time1_2', models.CharField(blank=True, max_length=100, null=True)),
                ('date2', models.CharField(blank=True, max_length=100, null=True)),
                ('time2_1', models.CharField(blank=True, max_length=100, null=True)),
                ('time2_2', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='store.car')),
            ],
        ),
    ]
