# Generated by Django 4.2.4 on 2023-08-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_testdrive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrive',
            old_name='time1_1',
            new_name='fra',
        ),
        migrations.RenameField(
            model_name='testdrive',
            old_name='time1_2',
            new_name='til',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='time2_1',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='time2_2',
        ),
    ]
