# Generated by Django 5.1 on 2026-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_bedrift_info_internal_notes_bedrift_info_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrift_info',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
