# Generated by Django 4.2.4 on 2023-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_time1_1_testdrive_fra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrive',
            old_name='fra',
            new_name='fra_1',
        ),
        migrations.RenameField(
            model_name='testdrive',
            old_name='til',
            new_name='fra_2',
        ),
        migrations.AddField(
            model_name='testdrive',
            name='til_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='til_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
