# Generated by Django 5.1 on 2026-08-29 16:40

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_bedrift_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(upload_to='business_images/', validators=[apps.store.models.validate_max_file_size]),
        ),
        migrations.AlterField(
            model_name='publicbusinessinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/', validators=[apps.store.models.validate_max_file_size]),
        ),
    ]
