# Generated by Django 5.1 on 2026-09-01 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_movelead_archived_movelead_archived_at_and_more'),
        ('store', '0015_alter_businessimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrift_info',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CoverageChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(blank=True, default='', max_length=255)),
                ('cities', models.CharField(blank=True, default='', max_length=255)),
                ('service_areas', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Venter på godkjenning'), ('approved', 'Godkjent'), ('rejected', 'Avvist')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_requests', to='store.bedrift_info')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Meldt'), ('approved', 'Kreditert'), ('rejected', 'Avslått')], default='requested', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_credits', to='store.bedrift_info')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='leads.movelead')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lead', 'business'), name='unique_lead_credit_per_business')],
            },
        ),
    ]
