# Generated by Django 4.2.4 on 2023-08-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_fra_testdrive_fra_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrive',
            old_name='fra_1',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='testdrive',
            old_name='fra_2',
            new_name='time2',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='til_1',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='til_2',
        ),
    ]
