# Generated by Django 4.2.4 on 2023-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_fra_1_testdrive_time1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
