# Generated by Django 4.2.4 on 2023-08-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_bud_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
