# Generated by Django 4.2.4 on 2023-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_bud_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner_mobile_nr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
