# Generated by Django 3.1.5 on 2023-05-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
