# Generated by Django 4.2.4 on 2023-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='steps',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4')], default='zero', max_length=20),
        ),
    ]
