# Generated by Django 3.1.5 on 2023-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact_by_phone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
