# Generated by Django 3.1.5 on 2023-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20230527_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
