# Generated by Django 4.2.4 on 2023-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_buy_forsikring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='forsikring',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
