# Generated by Django 4.2.4 on 2023-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_buy_forsikring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='forsikring',
            field=models.CharField(choices=[('no', 'Nei'), ('yes', 'Ja')], default='no', max_length=20),
        ),
    ]
