# Generated by Django 4.2.4 on 2023-08-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField(blank=True, default=0, max_length=300, null=True)),
                ('image1', models.ImageField(default='', upload_to='other/products/')),
                ('image2', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image3', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image4', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image5', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image6', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image7', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image8', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image9', models.ImageField(blank=True, default='', upload_to='other/products/')),
                ('image10', models.ImageField(blank=True, default='', upload_to='other/products/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
