# Generated by Django 4.2.4 on 2023-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_buy_forsikring'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='garanti',
            field=models.CharField(choices=[('no', 'Nei'), ('yes', 'Ja')], default='no', max_length=20),
        ),
    ]
