# Generated by Django 4.2.4 on 2023-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_car_remove_productreview_product_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='chasis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fritak_for_reg_pris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='mobile_nr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='post_nr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='reg_nr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='reg_pris',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
