# Generated by Django 4.2.4 on 2023-08-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_buy_garanti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='radi_FM',
            new_name='radio_FM',
        ),
    ]
