# Generated by Django 4.2.4 on 2023-08-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_car_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
