# Generated by Django 4.2.4 on 2023-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_radi_fm_car_radio_fm'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image11',
            field=models.ImageField(default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image12',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image13',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image14',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image15',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image16',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image17',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image18',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image19',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image20',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image21',
            field=models.ImageField(default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image22',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image23',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image24',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image25',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image26',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image27',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image28',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image29',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image30',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
    ]
