# Generated by Django 4.2.4 on 2023-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_car_image11_car_image12_car_image13_car_image14_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image11',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image21',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
    ]
