# Generated by Django 4.2.4 on 2023-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_car_image11_alter_car_image21'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(blank=True, default='Norge', max_length=100, null=True),
        ),
    ]
