# Generated by Django 4.2.4 on 2023-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
