# Generated by Django 4.2.4 on 2023-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_car_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='garanti_type',
            field=models.CharField(blank=True, choices=[('Nybilgaranti', 'Nybilgaranti'), ('Bruktbilgaranti', 'Bruktbilgaranti')], max_length=100, null=True),
        ),
    ]
