# Generated by Django 4.2.4 on 2023-09-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrive',
            old_name='date1',
            new_name='date1_Y_m_d',
        ),
        migrations.RenameField(
            model_name='testdrive',
            old_name='date2',
            new_name='date2_Y_m_d',
        ),
    ]
