# Generated by Django 4.2.4 on 2023-08-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_bud_car_days_until_expired_car_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='days_until_expired',
        ),
    ]
