# Generated by Django 4.2.4 on 2023-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_date1_testdrive_date1_y_m_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hjuldrift',
            field=models.CharField(blank=True, choices=[('Foranhjulsdrift', 'Foranhjulsdrift'), ('bBakhjulsdriftk', 'Bakhjulsdrift'), ['Firhjulsdrift', 'Firhjulsdrift']], max_length=200, null=True),
        ),
    ]
