# Generated by Django 4.2.4 on 2023-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_car_hjuldrift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hjuldrift',
            field=models.CharField(blank=True, choices=[('Forhjulsdrift', 'Forhjulsdrift'), ('bBakhjulsdriftk', 'Bakhjulsdrift'), ['Firhjulsdrift', 'Firhjulsdrift']], max_length=200, null=True),
        ),
    ]
