# Generated by Django 4.2.4 on 2023-08-13 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_car_days_until_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bud',
            name='name',
        ),
        migrations.AddField(
            model_name='bud',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bud',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bud',
            name='bidder_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bud',
            name='car',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='store.car'),
        ),
        migrations.AddField(
            model_name='bud',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bud',
            name='expiry_date',
            field=models.BooleanField(default=False),
        ),
    ]
