# Generated by Django 4.2.4 on 2023-08-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_bud_name_bud_bid_amount_bud_bid_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='car',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='store.car'),
        ),
    ]
