# Generated by Django 4.2.4 on 2023-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_car_hjuldrift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='garanti_type',
        ),
        migrations.AddField(
            model_name='car',
            name='garanti',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='service',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
