# Generated by Django 4.2.4 on 2023-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_bud_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bud',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bud',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
