# Generated by Django 4.2.4 on 2023-08-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_bud_accepted_alter_bud_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bud',
            name='bid_time',
        ),
    ]
