# Generated by Django 4.2.4 on 2023-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_car_garanti_alter_car_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image31',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image32',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image33',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image34',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image35',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image36',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image37',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image38',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image39',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image40',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image41',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image42',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image43',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image44',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image45',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image46',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image47',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image48',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image49',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image50',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image51',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image52',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image53',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image54',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image55',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image56',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image57',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image58',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image59',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image60',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image61',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image62',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image63',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image64',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image65',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image66',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image67',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image68',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image69',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image70',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image71',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image72',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image73',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image74',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image75',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image76',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image77',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image78',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image79',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image80',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
    ]
