# Generated by Django 4.1.3 on 2023-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_car_image31_car_image32_car_image33_car_image34_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bud',
            name='bid_amount',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
