# Generated by Django 4.1.3 on 2023-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_bud_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, default=0, max_length=300, null=True),
        ),
    ]
