# Generated by Django 4.2.4 on 2023-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
