# Generated by Django 4.2.4 on 2023-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_bud_car_alter_bud_user_alter_buy_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='car_spesifikasjoner',
        ),
        migrations.AlterField(
            model_name='car',
            name='chasis',
            field=models.CharField(blank=True, choices=[('Kombi-5', 'Kombi-5 dørs'), ('SUV', 'SUV')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drivstoff',
            field=models.CharField(blank=True, choices=[('Bensin', 'Bensin'), ('Diesel ', 'Diesel'), ('Elektrisk ', 'Elektrisk')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='garanti',
            field=models.TextField(blank=True, default='Denne bilen kan selges med bruktbilgaranti 24måneder eller frem til 200000km.', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='girkasse',
            field=models.CharField(blank=True, choices=[('Automat', 'Automat'), ('Manuelt ', 'Manuelt')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='service',
            field=models.TextField(blank=True, default='Bilens serviceprogram er fulgt. Det er tatt servicer på bilen i henhold til fabrikkens retningslinjer.', max_length=700, null=True),
        ),
    ]
