# Generated by Django 4.1.3 on 2023-10-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0042_rename_car_model_car_car_spesifikasjoner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egenerkeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='store.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egenerkling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
