# Generated by Django 4.1.3 on 2023-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_egenerkeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='mobile_nr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='personal_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
