# Generated by Django 4.1.3 on 2023-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_egenerkeling_account_number_egenerkeling_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='stepOne',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
