# Generated by Django 4.1.3 on 2023-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_egenerkeling_stepone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egenerkeling',
            name='stepOne',
            field=models.BooleanField(blank=True),
        ),
    ]
