# Generated by Django 4.1.3 on 2023-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_egenerkeling_stepone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egenerkeling',
            name='stepOne',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
