# Generated by Django 4.1.3 on 2023-10-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_egenerkeling_stepone'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='bruktimportert',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='demobil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='km',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='owners',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='reg_nr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='stepTwo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
