# Generated by Django 4.1.3 on 2023-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_egenerkeling_bruktimportert_egenerkeling_demobil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='file_tools',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='manual_tools',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
