# Generated by Django 4.1.3 on 2023-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_egenerkeling_file_tools_egenerkeling_manual_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='stepThree',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
