# Generated by Django 4.1.3 on 2023-10-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_egenerkeling_stepthree'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='next_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='service_history',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='stepFour',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='verksted_history',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
