# Generated by Django 4.1.3 on 2023-10-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_egenerkeling_next_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='batery',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='drivverk',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='karrosseri',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='left_garantier',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='new_car_garanti',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='stepFive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
