# Generated by Django 4.1.5 on 2023-10-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_egenerkeling_batery_egenerkeling_drivverk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
