# Generated by Django 4.1.5 on 2023-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=1000000000000000, null=True),
        ),
    ]
