# Generated by Django 4.1.3 on 2023-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hjuldrift',
            field=models.CharField(blank=True, choices=[('Forhjulsdrift', 'Forhjulsdrift'), ('Bakhjulsdrift', 'Bakhjulsdrift'), ['Firhjulsdrift', 'Firhjulsdrift']], max_length=200, null=True),
        ),
    ]
