# Generated by Django 4.1.3 on 2023-11-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_car_hjuldrift'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image81',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/cars/'),
        ),
    ]
