# Generated by Django 4.1.5 on 2023-11-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_car_image81'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image81',
        ),
    ]
