# Generated by Django 4.2.4 on 2023-11-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_carimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImages',
        ),
    ]
