# Generated by Django 4.2.4 on 2023-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_delete_carimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hjuldrift',
            field=models.CharField(blank=True, choices=[('Forhjulsdrift', 'Forhjulsdrift'), ('Bakhjulsdrift', 'Bakhjulsdrift'), ['Firehjulsdrift', 'Firehjulsdrift']], max_length=200, null=True),
        ),
    ]
