# Generated by Django 4.2.4 on 2023-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_car_hjuldrift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='chasis',
        ),
        migrations.AlterField(
            model_name='car',
            name='garanti',
            field=models.CharField(blank=True, default='Denne bilen kan selges med bruktbilgaranti 24måneder eller frem til 200000km.', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='karosseritype',
            field=models.CharField(blank=True, choices=[('Kombi-5 dørs', 'Kombi-5 dørs'), ('SUV/Offroad', 'SUV/Offroad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='service',
            field=models.CharField(blank=True, default='Bilens serviceprogram er fulgt. Det er tatt servicer på bilen i henhold til fabrikkens retningslinjer.', max_length=700, null=True),
        ),
    ]
