# Generated by Django 4.2.4 on 2023-11-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_remove_car_chasis_alter_car_garanti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='CD_spiller',
            new_name='cd_spiller',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='LED_lys',
            new_name='led_lys',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='TV_skjerm_i_baksetet',
            new_name='tv_skjerm_i_baksetet',
        ),
    ]
