# Generated by Django 4.2.4 on 2023-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_rename_cd_spiller_car_cd_spiller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drivstoff',
            field=models.CharField(blank=True, choices=[('Bensin', 'Bensin'), ('Diesel ', 'Diesel'), ('Elektrisk ', 'Elektrisk'), ('Hybrid ', 'Hybrid')], max_length=100, null=True),
        ),
    ]
