# Generated by Django 4.2.4 on 2023-11-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_alter_car_drivstoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='karosseritype',
            field=models.CharField(blank=True, choices=[('Kombi-5 dørs', 'Kombi-5 dørs'), ('SUV/Offroad', 'SUV/Offroad'), ('Sedan', 'Sedan'), ('Stasjonsvogn', 'Stasjonsvogn')], max_length=100, null=True),
        ),
    ]
