# Generated by Django 4.2.4 on 2023-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_alter_car_karosseritype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='girkasse',
            field=models.CharField(blank=True, choices=[('Automat', 'Automat'), ('Manuell ', 'Manuell')], max_length=100, null=True),
        ),
    ]
