# Generated by Django 4.2.4 on 2023-11-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_car_girkasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
