# Generated by Django 4.2.4 on 2023-11-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_car_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='thumbnail',
        ),
    ]
