# Generated by Django 4.1.5 on 2023-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_remove_car_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='karosseritype',
            field=models.CharField(blank=True, choices=[('Kombi-5 dørs', 'Kombi-5 dørs'), ('SUV/Offroad', 'SUV/Offroad'), ('Sedan', 'Sedan'), ('Stasjonsvogn', 'Stasjonsvogn'), ('Coupe', 'Coupe')], max_length=100, null=True),
        ),
    ]
