# Generated by Django 4.2.4 on 2023-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_alter_car_karosseritype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='map_images',
            field=models.ImageField(default='', upload_to='static/images/other/'),
        ),
    ]
