# Generated by Django 4.1.5 on 2023-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_car_map_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='map_images',
            field=models.ImageField(blank=True, default='', upload_to='static/images/other/'),
        ),
    ]
