# Generated by Django 4.1.5 on 2023-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_alter_car_map_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilder',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
