# Generated by Django 4.1.5 on 2023-11-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_egenerkeling_bruksmerker_bilder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egenerkeling',
            name='car',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='egenerkling', to='store.car'),
        ),
    ]
