# Generated by Django 4.1.5 on 2023-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_alter_egenerkeling_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egenerkeling',
            old_name='bruksmerker_bilder',
            new_name='bruksmerker_bilde1',
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde10',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde11',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde12',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde13',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde14',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde15',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
