# Generated by Django 4.1.5 on 2023-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_rename_bruksmerker_bilder_egenerkeling_bruksmerker_bilde1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde16',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde17',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde18',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde19',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde20',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
