# Generated by Django 4.1.5 on 2023-11-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_egenerkeling_bruksmerker_bilde16_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egenerkeling',
            name='bruksmerker_bilde8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
