# Generated by Django 4.2.4 on 2023-11-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_egenerkeling_bruksmerker_bilde8'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='skjul_annonsen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
