# Generated by Django 4.2.4 on 2023-12-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_car_skjul_annonsen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='karosseritype',
            field=models.CharField(blank=True, choices=[('Kombi-5 dørs', 'Kombi-5 dørs'), ('SUV/Offroad', 'SUV/Offroad'), ('Sedan', 'Sedan'), ('Stasjonsvogn', 'Stasjonsvogn'), ('Coupe', 'Coupe'), ('Pickup', 'Pickup')], max_length=100, null=True),
        ),
    ]
