# Generated by Django 4.1.5 on 2023-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_alter_car_karosseritype'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='phone_number',
            field=models.CharField(default=20, max_length=400),
            preserve_default=False,
        ),
    ]
