# Generated by Django 4.1.5 on 2023-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_testdrive_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='forsikring',
            field=models.CharField(choices=[('no', 'Nei'), ('yes', 'Ja')], default='--', max_length=20),
        ),
    ]
