# Generated by Django 4.1.5 on 2023-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_alter_buy_forsikring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='forsikring',
            field=models.CharField(choices=[('no', 'Nei'), ('yes', 'Ja')], default='no', max_length=20),
        ),
    ]
