# Generated by Django 4.1.5 on 2023-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_alter_buy_forsikring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde10',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde11',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde12',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde13',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde14',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde15',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde16',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde17',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde18',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde19',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde20',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde4',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde5',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde6',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde7',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde8',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='bruksmerker_bilde9',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/other/cars/'),
        ),
    ]
