# Generated by Django 4.1.5 on 2023-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_alter_egenerkeling_bruksmerker_bilde1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='steps',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('three-half', '3.5'), ('four', '4')], default='zero', max_length=20),
        ),
    ]
