# Generated by Django 4.1.5 on 2023-12-20 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_alter_buy_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
