# Generated by Django 4.1.5 on 2023-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_car_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.CharField(blank=True, choices=[('Cecilie Gromsrud', 'Cecilie Gromsrud'), ('Fredrik S. von der Lippe', 'Fredrik S. von der Lippe'), ('Øystein Helgheim', 'Øystein Helgheim'), ('Frederik F. Mørk', 'Frederik F. Mørk')], max_length=300, null=True),
        ),
    ]
