# Generated by Django 4.1.5 on 2023-12-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_alter_car_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.car')),
            ],
        ),
    ]
