# Generated by Django 4.1.5 on 2023-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_soldcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egenerkeling',
            name='file_tools',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='service_history',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='static/images/other/cars/'),
        ),
        migrations.AlterField(
            model_name='egenerkeling',
            name='verksted_history',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='static/images/other/cars/'),
        ),
    ]
