# Generated by Django 4.1.5 on 2023-12-22 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_alter_egenerkeling_file_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
