# Generated by Django 4.1.5 on 2023-12-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_soldcar_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
