# Generated by Django 5.1 on 2025-10-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flytteforesporsel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(blank=True, max_length=100, null=True)),
                ('from_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('from_city', models.CharField(blank=True, max_length=100, null=True)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('to_city', models.CharField(blank=True, max_length=100, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('move_help', models.CharField(blank=True, max_length=255, null=True)),
                ('from_property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('to_property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('from_rooms', models.CharField(blank=True, max_length=50, null=True)),
                ('to_rooms', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
