# Generated by Django 5.1 on 2025-10-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('store', '0005_jobdistribution_slot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flytteforesporsel',
            name='business_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_leads', to='store.bedrift_info', verbose_name='Business 1'),
        ),
        migrations.AddField(
            model_name='flytteforesporsel',
            name='business_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_leads', to='store.bedrift_info', verbose_name='Business 2'),
        ),
        migrations.AddField(
            model_name='flytteforesporsel',
            name='business_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_leads', to='store.bedrift_info', verbose_name='Business 3'),
        ),
    ]
