# Generated by Django 4.1.5 on 2023-08-04 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cords1', models.CharField(blank=True, max_length=150)),
                ('cords2', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to='static/images/other/user_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verdivurdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_nr', models.CharField(max_length=200)),
                ('km', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('vilkaar', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Websites',
        ),
    ]
