# Generated by Django 5.1 on 2025-10-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flytteforesporsel_business_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flytteforesporsel',
            name='business_1',
        ),
        migrations.RemoveField(
            model_name='flytteforesporsel',
            name='business_2',
        ),
        migrations.RemoveField(
            model_name='flytteforesporsel',
            name='business_3',
        ),
    ]
