# Generated by Django 5.1 on 2025-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_flytteforesporsel_business_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flytteforesporsel',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='flytteforesporsel',
            name='from_kvm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flytteforesporsel',
            name='move_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flytteforesporsel',
            name='move_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flytteforesporsel',
            name='to_kvm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
