# Generated by Django 5.1 on 2025-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_flytteforesporsel_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flytteforesporsel',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
