# Generated by Django 5.1 on 2026-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flytteforesporsel_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(help_text='Static path, e.g. images/home/loeftlogo.svg', max_length=255)),
                ('logo_blend_multiply', models.BooleanField(default=False)),
                ('tagline', models.CharField(max_length=200)),
                ('short', models.TextField()),
                ('about', models.JSONField(default=list, help_text='List of paragraph strings')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_count', models.PositiveIntegerField()),
                ('jobs_completed', models.PositiveIntegerField()),
                ('response_time', models.CharField(max_length=100)),
                ('member_since', models.PositiveIntegerField()),
                ('services', models.JSONField(default=list, help_text='List of strings')),
                ('areas', models.JSONField(default=list, help_text='List of strings')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_role', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50)),
                ('reviews', models.JSONField(default=list, help_text='List of {name, date, stars, service, comment}')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('ingress', models.TextField()),
                ('header_image', models.URLField(blank=True, default='', max_length=500)),
                ('date', models.DateField()),
                ('read_minutes', models.PositiveIntegerField()),
                ('blocks', models.JSONField(default=list, help_text="List of {type, text} | {type:'list', items} | {type:'image', src, alt, caption} | {type:'cta'}")),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
