# Generated by Django 4.2.4 on 2023-08-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_date_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
