# Generated by Django 4.2.4 on 2023-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_younger_than_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='less_than_150000km',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sms_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='vilkaar',
            field=models.BooleanField(default=False),
        ),
    ]
