# Generated by Django 4.2.4 on 2023-08-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_car_younger_than_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_younger_than_10',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='less_than_150000km',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sms_reminder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vilkaar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
