# Generated by Django 4.1.5 on 2023-09-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
