# Generated by Django 4.1.3 on 2023-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visning',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
