# Generated by Django 4.2.4 on 2023-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_visning_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
