# Generated by Django 4.2.4 on 2023-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profile_image_profile_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fakturert',
            field=models.BooleanField(default=False),
        ),
    ]
