# Generated by Django 4.2.4 on 2023-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20230727_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cords1', models.CharField(blank=True, max_length=150)),
                ('cords2', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Verdivurdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_nr', models.CharField(max_length=200)),
                ('km', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('vilkaar', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
    ]
