# Generated by Django 3.1.5 on 2023-08-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20230727_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('preference', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=15, null=True)),
                ('checkbox1', models.BooleanField(default=False)),
                ('checkbox2', models.BooleanField(default=False)),
                ('checkbox3', models.BooleanField(default=False)),
                ('km', models.CharField(blank=True, max_length=15, null=True)),
                ('car_name_model', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(8, '08:00'), (10, '10:00'), (12, '12:00'), (14, '14:00')])),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
