# Generated by Django 4.2.4 on 2023-08-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_date',
            new_name='is_booked',
        ),
    ]
