# Generated by Django 4.2.4 on 2023-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_booked_date_booking_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reg_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reg_nr',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_name_model',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='km',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preference',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('08:00', '08:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00')], max_length=5),
        ),
    ]
