# Generated by Django 4.2.4 on 2023-08-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_booking_day_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reg_nr',
            new_name='reg_number',
        ),
    ]
