# Generated by Django 4.2.4 on 2023-08-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_reg_nr_booking_reg_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reg_number',
            new_name='reg_nr',
        ),
    ]
