# Generated by Django 4.2.4 on 2023-08-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_reg_number_booking_reg_nr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
