# Generated by Django 4.2.4 on 2023-08-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdivurdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
    ]
