# Generated by Django 4.2.4 on 2023-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_verdivurdering'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdivurdering',
            name='vilkaar',
            field=models.BooleanField(default=False),
        ),
    ]
