# Generated by Django 4.2.4 on 2023-08-04 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_verdivurdering_vilkaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdivurdering',
            name='km',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verdivurdering',
            name='reg_nr',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
