# Generated by Django 5.1 on 2026-08-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('flytte_type', models.CharField(choices=[('privat', 'Privat'), ('bedrift', 'Bedrift'), ('internasjonal', 'Internasjonal')], max_length=20)),
                ('boligtype', models.CharField(choices=[('leilighet', 'Leilighet'), ('rekkehus', 'Rekkehus'), ('enebolig', 'Enebolig'), ('annet', 'Annet')], max_length=20)),
                ('fra', models.CharField(max_length=255)),
                ('fra_lat', models.FloatField(blank=True, null=True)),
                ('fra_lon', models.FloatField(blank=True, null=True)),
                ('til', models.CharField(max_length=255)),
                ('til_lat', models.FloatField(blank=True, null=True)),
                ('til_lon', models.FloatField(blank=True, null=True)),
                ('flyttedato', models.DateField(blank=True, null=True)),
                ('fleksibel', models.BooleanField(default=False)),
                ('beskrivelse', models.TextField(blank=True, default='')),
                ('navn', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=50)),
                ('epost', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leads.movelead')),
            ],
        ),
    ]
