# Generated by Django 5.1 on 2026-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelead',
            name='status',
            field=models.CharField(choices=[('new', 'Ny'), ('contacted', 'Kontaktet'), ('booked', 'Bestilt')], default='new', max_length=20),
        ),
    ]
