# Generated by Django 5.1 on 2026-08-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_movelead_status'),
        ('store', '0010_bedrift_info_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelead',
            name='business_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_primary', to='store.bedrift_info'),
        ),
        migrations.AddField(
            model_name='movelead',
            name='business_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_secondary', to='store.bedrift_info'),
        ),
        migrations.AddField(
            model_name='movelead',
            name='business_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_tertiary', to='store.bedrift_info'),
        ),
    ]
