# Generated by Django 4.1.5 on 2026-08-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_movelead_business_1_movelead_business_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelead',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movelead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movelead',
            name='follow_up_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movelead',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
