# Generated by Django 5.1 on 2026-09-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_movelead_archived_movelead_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=32, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('verified_address', models.JSONField()),
                ('normalized', models.JSONField()),
                ('selected_unit_number', models.CharField(blank=True, default='', max_length=20)),
                ('data_source', models.CharField(default='api', max_length=10)),
                ('manual_overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_bnr',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_bra_m2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_byggeaar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_datakilde',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_enhet',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_etasjer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_gnr',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='movelead',
            name='bolig_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movelead',
            name='property_lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.propertylookup'),
        ),
    ]
