# Generated by Django 5.1 on 2026-09-02 15:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_normalized_contact(apps, schema_editor):
    """Populate telefon_normalisert / epost_normalisert on existing leads so
    repeat-submission detection sees history from before this feature."""
    from apps.leads.duplicates import normalize_email, normalize_phone

    MoveLead = apps.get_model("leads", "MoveLead")
    updates = []
    for lead in MoveLead.objects.all().only("id", "telefon", "epost"):
        lead.telefon_normalisert = normalize_phone(lead.telefon)
        lead.epost_normalisert = normalize_email(lead.epost)
        updates.append(lead)
    if updates:
        MoveLead.objects.bulk_update(updates, ["telefon_normalisert", "epost_normalisert"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_propertylookup_movelead_bolig_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelead',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_submissions', to='leads.movelead'),
        ),
        migrations.AddField(
            model_name='movelead',
            name='epost_normalisert',
            field=models.CharField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='movelead',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movelead',
            name='telefon_normalisert',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_normalized_contact, migrations.RunPython.noop),
    ]
