# Generated by Django 5.1 on 2026-08-21 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('path', models.CharField(help_text='Ekte URL, f.eks. /om-oss/', max_length=200, unique=True)),
                ('template_key', models.CharField(choices=[('home', 'Forside'), ('about', 'Om oss'), ('for_business', 'For bedrifter'), ('contact', 'Kontakt')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Utkast'), ('published', 'Publisert')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('image_strip', 'Bildestripe'), ('stats', 'Statistikk'), ('services', 'Tjenester'), ('testimonials', 'Kundeuttalelser'), ('faq', 'Ofte stilte spørsmål'), ('how_it_works', 'Slik fungerer det'), ('trust', 'Tillit'), ('cta', 'Call-to-action'), ('footer', 'Footer'), ('generic_text', 'Generisk tekst')], max_length=30)),
                ('heading', models.CharField(blank=True, default='', max_length=300)),
                ('subheading', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('button_label', models.CharField(blank=True, default='', max_length=100)),
                ('button_href', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['page', 'order'],
            },
        ),
    ]
