# Generated by Django 5.1 on 2026-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('image_strip', 'Bildestripe'), ('stats', 'Statistikk'), ('services', 'Tjenester'), ('testimonials', 'Kundeuttalelser'), ('faq', 'Ofte stilte spørsmål'), ('how_it_works', 'Slik fungerer det'), ('trust', 'Tillit'), ('cities', 'Byer'), ('cta', 'Call-to-action'), ('footer', 'Footer'), ('generic_text', 'Generisk tekst')], max_length=30),
        ),
    ]
