# Generated by Django 5.1 on 2026-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Vises under tittelen i søkeresultater.', max_length=160),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Vises i nettleserfanen og søkeresultater. Tomt = sidetittel.', max_length=70),
        ),
    ]
