# Generated by Django 4.1.5 on 2026-08-26 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_page_meta_description_page_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PageSectionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('heading', 'Overskrift'), ('subheading', 'Underoverskrift'), ('body_text', 'Brødtekst'), ('button_label', 'Knappetekst'), ('button_href', 'Knapp-lenke')], max_length=30)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pages.pagesection')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
