from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("logg-inn/", views.dashboard_login, name="login"),
    path("logg-ut/", views.dashboard_logout, name="logout"),
    path("", views.dashboard_overview, name="dashboard_overview"),
    path("sok/", views.global_search, name="global_search"),
    path("leads/", views.lead_list, name="lead_list"),
    path("lead/eksporter/", views.lead_export_csv, name="lead_export_csv"),
    path("lead/bulk/", views.lead_bulk_action, name="lead_bulk_action"),
    path("papirkurv/", views.lead_trash, name="lead_trash"),
    path("papirkurv/<int:pk>/gjenopprett/", views.lead_restore, name="lead_restore"),
    path("papirkurv/<int:pk>/slett/", views.lead_permanent_delete, name="lead_permanent_delete"),
    path("lead/<int:pk>/", views.lead_detail, name="lead_detail"),
    path("lead/<int:pk>/status/", views.update_status, name="update_status"),
    path("lead/<int:pk>/notater/", views.lead_update_internal, name="lead_update_internal"),
    path("lead/<int:pk>/arkiver/", views.lead_archive, name="lead_archive"),
    path("lead/<int:pk>/tildel/", views.lead_assign_businesses, name="lead_assign_businesses"),
    path("sider/", views.page_list, name="page_list"),
    path("sider/<int:pk>/publiser/", views.page_toggle_status, name="page_toggle_status"),
    path("sider/<int:pk>/metadata/", views.page_update_meta, name="page_update_meta"),
    path("sider/<int:pk>/dupliser/", views.page_duplicate, name="page_duplicate"),
    path("sider/<int:pk>/slett/", views.page_delete, name="page_delete"),
    path("sider/<int:pk>/planlegg/", views.page_schedule_publish, name="page_schedule_publish"),
    path("sider/<int:pk>/historikk/", views.page_history, name="page_history"),
    path("sider/seksjon/<int:pk>/felt/", views.section_inline_update, name="section_inline_update"),
    path("sider/seksjon/<int:pk>/element/<int:index>/", views.section_list_item_update, name="section_list_item_update"),
    path("sider/seksjon/<int:pk>/element/legg-til/", views.section_list_item_add, name="section_list_item_add"),
    path("sider/seksjon/<int:pk>/element/<int:index>/slett/", views.section_list_item_delete, name="section_list_item_delete"),
    path("sider/seksjon/<int:pk>/element/<int:index>/bilde/", views.section_list_item_image, name="section_list_item_image"),
    path("sider/revisjon/<int:pk>/gjenopprett/", views.section_revision_restore, name="section_revision_restore"),
    path("blogg/", views.article_list, name="article_list"),
    path("blogg/ny/", views.article_add, name="article_add"),
    path("blogg/<int:pk>/rediger/", views.article_edit, name="article_edit"),
    path("blogg/<int:pk>/slett/", views.article_delete, name="article_delete"),
    path("bedrifter/", views.business_list, name="business_list"),
    path("bedrifter/importer/", views.business_import, name="business_import"),
    path("bedrifter/<int:pk>/", views.business_detail, name="business_detail"),
    path("bedrifter/<int:pk>/aktiver/", views.business_toggle_active, name="business_toggle_active"),
    path("bedrifter/<int:pk>/bilde/legg-til/", views.business_image_add, name="business_image_add"),
    path("bedrifter/<int:pk>/bilde/<int:image_pk>/slett/", views.business_image_delete, name="business_image_delete"),
    path("bedrifter/<int:pk>/anmeldelse/legg-til/", views.review_add, name="review_add"),
    path("bedrifter/<int:pk>/anmeldelse/<int:review_pk>/rediger/", views.review_edit, name="review_edit"),
    path("bedrifter/<int:pk>/anmeldelse/<int:review_pk>/slett/", views.review_delete, name="review_delete"),
    path("aktivitetslogg/", views.activity_log, name="activity_log"),
]
