# Generated by Django 4.2.7 on 2024-03-07 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telefon', models.CharField(blank=True, max_length=150, null=True)),
                ('medlemskap', models.CharField(blank=True, choices=[('Bruker', 'Bruker'), ('Vanlig', 'Vanlig'), ('Pro', 'Pro'), ('Pro+', 'Pro+')], max_length=150, null=True)),
                ('price', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, default='static/images/other/user-default.jpg', upload_to='other/users/')),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
