# Generated by Django 4.2.7 on 2024-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_id_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_nr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
