# Generated by Django 4.2.4 on 2024-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_org_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/other/user-default.jpg', upload_to='static/other/users/'),
        ),
    ]
