# Generated by Django 4.2.7 on 2024-03-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_subscription_change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
