# Generated by Django 5.1 on 2025-03-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_last_subscription_change_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telefon',
        ),
    ]
