# Generated by Django 5.1 on 2025-03-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_profile_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_subscription_change_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medlemskap',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='org_nr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(default=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(default=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(default=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(default=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefon',
            field=models.CharField(default=True, max_length=1000, null=True),
        ),
    ]
